package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZhilianjob<M extends BaseZhilianjob<M>> extends Model<M> implements IBean {

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setZwmc(java.lang.String zwmc) {
		set("zwmc", zwmc);
	}

	public java.lang.String getZwmc() {
		return get("zwmc");
	}

	public void setGsmc(java.lang.String gsmc) {
		set("gsmc", gsmc);
	}

	public java.lang.String getGsmc() {
		return get("gsmc");
	}

	public void setZwyx(java.lang.String zwyx) {
		set("zwyx", zwyx);
	}

	public java.lang.String getZwyx() {
		return get("zwyx");
	}

	public void setZwdd(java.lang.String zwdd) {
		set("zwdd", zwdd);
	}

	public java.lang.String getZwdd() {
		return get("zwdd");
	}

	public void setFbrq(java.lang.String fbrq) {
		set("fbrq", fbrq);
	}

	public java.lang.String getFbrq() {
		return get("fbrq");
	}

	public void setGzxz(java.lang.String gzxz) {
		set("gzxz", gzxz);
	}

	public java.lang.String getGzxz() {
		return get("gzxz");
	}

	public void setGzjy(java.lang.String gzjy) {
		set("gzjy", gzjy);
	}

	public java.lang.String getGzjy() {
		return get("gzjy");
	}

	public void setZdxl(java.lang.String zdxl) {
		set("zdxl", zdxl);
	}

	public java.lang.String getZdxl() {
		return get("zdxl");
	}

	public void setZprs(java.lang.String zprs) {
		set("zprs", zprs);
	}

	public java.lang.String getZprs() {
		return get("zprs");
	}

	public void setZwlb(java.lang.String zwlb) {
		set("zwlb", zwlb);
	}

	public java.lang.String getZwlb() {
		return get("zwlb");
	}

}
