package com.demo.common.model;

import com.demo.common.model.base.BaseSqoopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sqoopy extends BaseSqoopy<Sqoopy> {
	public static final Sqoopy dao = new Sqoopy();
}
