package com.demo.common.model;

import com.demo.common.model.base.BaseZhilianjob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zhilianjob extends BaseZhilianjob<Zhilianjob> {
	public static final Zhilianjob dao = new Zhilianjob();
}
