package com.demo.common.model;

import com.demo.common.model.base.BaseZljob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zljob extends BaseZljob<Zljob> {
	public static final Zljob dao = new Zljob();
}
